version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Root1234"
      MYSQL_DATABASE: "bookstore_db"
      MYSQL_USER: "clarusway"
      MYSQL_PASSWORD: "Clarusway_1"
    networks:
      - development


  webserver:
    image: anilkaynar/bookstoreapi:latest
    container_name: bookstore-app
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - development

networks:
  development: